### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by fabioneves** [mancuniancol/script.magnetic.extratorrent-mc#1] opened 2016-07-21 16:39 UTC
Hello!
I've been using magnetic bridge with quasar, most of the providers work except this one.
I always get an error, log:
17:27:15 T:1444796720  NOTICE: [script.magnetic.extratorrent-mc] Accepted Keywords: ['1080p']
17:27:15 T:1444796720  NOTICE: [script.magnetic.extratorrent-mc] Blocked Keywords: ['CAM', 'TeleSync', 'Trailer']
17:27:15 T:1444796720  NOTICE: [script.magnetic.extratorrent-mc] min Size: 0.0 GB
17:27:15 T:1444796720  NOTICE: [script.magnetic.extratorrent-mc] max Size: MAX
17:27:15 T:1444796720   ERROR: Exception in thread Thread-1:
                                            Traceback (most recent call last):
                                              File "/var/lib/jenkins/jobs/SPMC-Custom-ARM/workspace/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/threading.py", line 532, in __bootstrap_inner
                                              File "/var/lib/jenkins/jobs/SPMC-Custom-ARM/workspace/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/threading.py", line 484, in run
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/script.module.magnetic/resources/provider.py", line 742, in execute_process
                                                read_magnet_link, verify_name, verify_size))
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/script.module.magnetic/resources/provider.py", line 634, in generate_payload
                                                for name, info_hash, magnet, size, seeds, peers in generator:
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/script.magnetic.extratorrent-mc/main.py", line 9, in extract_torrents
                                                dom = Html().feed(Filtering.normalize2(html))
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/script.module.magnetic/resources/ehp.py", line 1110, in feed
                                                HTMLParser.feed(self, data)
                                              File "/var/lib/jenkins/jobs/SPMC-Custom-ARM/workspace/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/HTMLParser.py", line 108, in feed
                                              File "/var/lib/jenkins/jobs/SPMC-Custom-ARM/workspace/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/HTMLParser.py", line 150, in goahead
                                              File "/var/lib/jenkins/jobs/SPMC-Custom-ARM/workspace/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/HTMLParser.py", line 314, in parse_endtag
                                              File "/var/lib/jenkins/jobs/SPMC-Custom-ARM/workspace/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/HTMLParser.py", line 115, in error
                                            HTMLParseError: bad end tag: "</scr'+'ipt>", at line 207, column 21
17:27:15 T:1444796720  NOTICE: [script.module.magnetic] Provider script.magnetic.extratorrent-mc returned 0 results in 0.8 seconds
17:27:16 T:1438628144  NOTICE: [script.module.magnetic] Applying quality sorting
17:27:16 T:1438628144  NOTICE: [script.module.magnetic] Providers search returned: 0 results in 0.8 seconds
17:27:16 T:1438628144  NOTICE: [script.module.magnetic] Filtering returned: 0 results

Thank you for your work!

**Comment by mancuniancol** [comment] 2016-07-22 10:15
Are you sure that you are using the latest working url?  http://extratorrent.cc/

I've tested and it is working without problem.  The default is not working.  But, I don't keep that updated because sometimes changes the one day to other sorry.

I will close this issue, because I cannot reproduce your claim.

**Comment by fabioneves** [comment] 2016-07-22 10:16
I'll try again with that URL, thanks for replying!

**Closed by mancuniancol** 2016-07-22 10:15 UTC
